進捗画面へのUIパーツの配置とAssetsのImage追加
yasasii-team/Stepippo-iOS pull request #109
Opened 2019-05-05 18:44 UTC by eyener3

fixes #87 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- StoryboardへUIパーツの配置

- AssetsへのImageを追加

### Other Information(他の情報)

- アクションシートとStackViewは別Issueを立てる

### Tested(テストしたこと)

- シュミレーターが立ち上がらないのでテストできず...

### Must Reviewer(必須レビュアー)
@Riscait

2019-05-06 00:16 UTC, riscait requested changes
配置が目に見えると良いですね✨
ProgressBarとCheckboxは仮の配置で、これから専用のクラスを作っていくって認識で合ってますよね😊？
エラーが出てる際は、エラー文をコピペするのとスクリーンショットがあると助かります👌
2箇所にコメントしました！

2019-05-06 00:16 UTC, riscait commented on Stepippo.xcodeproj/project.pbxproj
> +		0B04AA7B227A9DB200E18F0A /* Prog.storyboard */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Prog.storyboard; path = "/Users/katouayana/Xcode/Stepippo-iOS/Stepippo/Classes/
ここ、あいなーさんのローカルパスになっちゃってますね🤔
LocationをAbsoluteに変更したのが原因かと思います。
他のファイルに合わせて元に戻して、パスも正しましょう👌

2019-05-06 00:16 UTC, Riscait commented on Stepippo/Classes/Views/Prog.storyboard
> +                            <textField opaque="NO" contentMode="scaleToFill" fixedFrame="YES" contentHorizontalAlignment="left" contentVerticalAlignment="center" text="進捗" borderStyle="roundedRect" t
画面タイトルは、NavigationBarのTitleに設定しますのでここではTextFieldは不要ですね👌
MiscVCをみていただければわかりますが、コードで設定する方法とStoryboardで設定する方法の2種類があります！

2019-05-06 05:41 UTC, eyener3 commented
> 配置が目に見えると良いですね✨
ありがとうございます😊！

> ProgressBarとCheckboxは仮の配置で、これから専用のクラスを作っていくって認識で合ってますよね😊？
はい、その認識で合っています！💡

> エラーが出てる際は、エラー文をコピペするのとスクリーンショットがあると助かります👌
ありがとうございますっ
storyboardの作業をはじめてからずっと同じエラーが出ていて、
途方に暮れておりまして..後日うかがおうと思っておりました＞＜。
スクリーンショットとエラー文のコピペ送らせていただきますねっ

2019-05-06 05:52 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                            <textField opaque="NO" contentMode="scaleToFill" fixedFrame="YES" contentHorizontalAlignment="left" contentVerticalAlignment="center" text="進捗" borderStyle="roundedRect" t
詳しく教えていただき、
ありがとうございます^-^！

龍之介さんのMiscVCをもう一度見て、
コードとStoryboardとの設定の違いを、
ちゃんと理解したいと思います🙇🏻‍♀️✨

2019-05-06 05:54 UTC, eyener3 commented on Stepippo.xcodeproj/project.pbxproj
> +		0B04AA7B227A9DB200E18F0A /* Prog.storyboard */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Prog.storyboard; path = "/Users/katouayana/Xcode/Stepippo-iOS/Stepippo/Classes/
ありがとうございます🙇🏻‍♀️🙏
色々といじっているうちに、
変更してしまっていたようです..＞＜
元に戻して、パスも正せるようにしてみます💡

2019-05-06 05:55 UTC, eyener3 commented
> 配置が目に見えると良いですね✨

ありがとうございます😊！

> ProgressBarとCheckboxは仮の配置で、これから専用のクラスを作っていくって認識で合ってますよね😊？

はい、その認識で合っています！💡

> エラーが出てる際は、エラー文をコピペするのとスクリーンショットがあると助かります👌

ありがとうございますっ
storyboardの作業をはじめてからずっと同じエラーが出ていて、
途方に暮れておりまして..後日うかがおうと思っておりました＞＜。
スクリーンショットとエラー文のコピペ送らせていただきますねっ

2019-05-06 11:49 UTC, eyener3 commented
- ローカルパスの修正を行ないました

- シュミレーター時のエラー文
`framework not found Realm`
![スクリーンショット 2019-05-06 20 44 27](https://user-images.githubusercontent.com/45029154/57223128-f6f4ce00-703f-11e9-9487-aea0967f736d.png)

- TextField「進捗」を消しました

よろしくお願いします^-^💡

2019-05-06 11:54 UTC, Riscait commented
> * シュミレーター時のエラー文
>   `framework not found Realm`

@eyener3 #76 こちらのIssueは完了しましたか？🤔
エラー読むと、Realmが入ってないからって言ってますよね、carthage bootstrapコマンドでライブラリをビルドすれば消えるかと思います👌

2019-05-06 11:58 UTC, Riscait commented
@eyener3 commitがPushされていないようです💡

2019-05-06 12:17 UTC, eyener3 commented
> > * シュミレーター時のエラー文
> >   `framework not found Realm`
> 
> @eyener3 #76 こちらのIssueは完了しましたか？🤔
> エラー読むと、Realmフレームワークがないからって言ってますよね、carthage bootstrapコマンドでフレームワークを作れば消えるかと思います👌

#76 まだできていないのですよね..
それが原因だと思うのですが、
何度、挑戦しても上手くいかずで..
近日中に教えていただこうと思っておりました🙇🏻‍♀️🙏

あ、pushしていないから、
フレームワークが反映されていないということなのでしょうかね><
もう一度、見直してみようと思います！
ありがとうございます😊

2019-05-07 07:13 UTC, eyener3 commented
pushしました^-^💡

2019-05-08 16:06 UTC, closed without merging