進捗画面のStackView作成と規約設定を行ないました
yasasii-team/Stepippo-iOS pull request #127
Opened 2019-05-09 21:31 UTC by eyener3

fixes #98 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- 各パーツをStackViewでまとめました
　- まとめたあとにレイアウトの設定を行ないました

### Other Information(他の情報)
- タスク完了時の字消しのボーダーを一旦削除しています

- 期間変更やタスクの選択・変更のボタンは今後、別Issueでカスタマイズしてみようと思います。

### Tested(テストしたこと)
ビルドエラーなく、シュミレーターでも問題なく表示されました
![スクリーンショット 2019-05-10 06 20 26](https://user-images.githubusercontent.com/45029154/57488002-dc934c80-72ec-11e9-8e71-05a2c6348dd3.png)
![スクリーンショット 2019-05-10 06 20 44](https://user-images.githubusercontent.com/45029154/57488015-e321c400-72ec-11e9-98bd-2efb2cce2761.png)

### Must Reviewer(必須レビュアー)

2019-05-09 21:35 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -                            <button opaque="NO" contentMode="scaleToFill" fixedFrame="YES" contentHorizontalAlignment="center" contentVerticalAlignment="center" buttonType="roundedRect" lineBreakMode
パーツの位置やサイズ、文字色変更などの微調整を行ないました。

2019-05-09 21:37 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
パーツの位置やサイズ、文字色変更などの微調整を行ないました。

2019-05-09 23:53 UTC, Riscait commented
おぉ、お疲れ様です！
帰ったら確認したいと思います👌

規約→制約ですね🙆‍♂️

FailesChangesはきっとFiles Changedのことですね？
おそらくPendingになっていそうです。（こちらからはあいなーさんがしたであろうコメントがまだ見えない）
Start Reviewからコメント残したら、（たぶん）右上に表示されているところからレビューを確定しましょう！

2019-05-10 00:47 UTC, eyener3 reviewed
よろしくお願いします^-^！

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +    <color key="tintColor" white="0.66666666666666663" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
完了タスクの「一人で映画鑑賞」の文字色を変更した

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -        <image name="border角太 黒" width="24" height="24"/>
完了タスク時の字消し線はコード実装するため、一旦削除した

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -                            </button>
StackViewがうまくいかなったため、⌘z で初期状態まで戻った

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                            </stackView>
StackViewで各パーツをまとめて、レイアウトの調整もした

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                        </constraints>
checkbuttonの配置を調整した

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
レイアウトエラーの自動修正を行なった

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                            <progressView opaque="NO" contentMode="scaleToFill" verticalHuggingPriority="750" progress="0.59999999999999998" translatesAutoresizingMaskIntoConstraints="NO" id="3EQ-lN-
Progressbarの長さを少し引き伸ばした

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                            <progressView opaque="NO" contentMode="scaleToFill" verticalHuggingPriority="750" progress="0.69999999999999996" translatesAutoresizingMaskIntoConstraints="NO" id="HjK-iW-
StackViewで各パーツをまとめて、レイアウトの調整もした

2019-05-10 00:47 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> -                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
はじめに文字サイズやパーツの配置を再調整しました。

2019-05-10 13:24 UTC, riscait requested changes
Progress ViewがStackViewに入っておらず、独立しているようです！
StackViewに含めましょう👌

2019-05-10 13:45 UTC, Riscait commented
iPhone8以下のデバイスで表示してみると、全ての要素が表示しきれず下部が欠けてしまいました。
下からの制約を追加してiPhone SEの画面サイズでも収まるようにするか、
UIScrollViewを使ってスクロール可能にしないといけないようです💡

2019-05-11 05:41 UTC, eyener3 commented
> Progress ViewがStackViewに入っておらず、独立しているようです！
> StackViewに含めましょう👌

たしかに、含めていませんでした..＞＜🙇‍♀️
含めてやってみます^0^

> iPhone8以下のデバイスで表示してみると、全ての要素が表示しきれず下部が欠けてしまいました。
> 下からの制約を追加してiPhone SEの画面サイズでも収まるようにするか、
> UIScrollViewを使ってスクロール可能にしないといけないようです💡

こちらもやってみます^-^！
他のデバイスで確認することしていなかったので
これからは、その辺りも"テストすること"に含めてみますm(._.)m💡

2019-05-11 17:24 UTC, eyener3 commented
案の定、コンフリクト起こしてしまっていたので
該当箇所を削除しましたm(._.)m

2019-05-11 19:48 UTC, eyener3 commented on Stepippo/Classes/Views/Prog.storyboard
> +                                    </stackView>
ProgressBarをStackViewに追加

2019-05-14 13:22 UTC, riscait approved these changes
ProgressViewがStackViewに含まれていること
エラーなくビルドできることを確認しました！

このPRはこれにて完了にしましょう🎉

2019-05-14 13:25 UTC, eyener3 commented
ありがとうございます！m(._.)m
今回、ゴチャゴチャしてしまって、
同じブランチでいろんなタスクをcommitすることでしか
解決できずに、申し訳ありませんでした＞＜。
今回の反省を次回に活かします🙇‍♀️

マージさせていただきます^-^💡

2019-05-14 13:33 UTC, eyener3 commented
こちらもマージではなく、closeでいいのでしょうか^-^？

2019-05-14 14:28 UTC, naipaka approved these changes
こちらでもProgressViewがStackViewの中に入っていることが確認できました！

2019-05-14 14:32 UTC, eyener3 commented
> こちらでもProgressViewがStackViewの中に入っていることが確認できました！

ないぱかさん、
ありがとうございます^0^！！

2019-05-14 14:32 UTC, merged