Xcodeプロジェクトのフォルダ構成を整理整頓する
yasasii-team/Stepippo-iOS pull request #13
Opened 2019-03-31 16:48 UTC by eyener3

2019-04-01 04:13 UTC, riscait requested changes
- チームをNoneに
- グループ名（フォルダ名）を変更
- リンク切れがあれば修正

が必要かと思います👌

あとアサイニーはあいなーさんに、
レビュワーにはゆーとさんとやまたつさんを追加しましょう〜(๑•̀ㅂ•́)و✧

2019-04-01 04:13 UTC, riscait commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
ここは、人それぞれ設定値が違うところになりますので、`""` となることが期待値です👌
今回は、teamをNoneに戻してコミットしましょう👍
<img width="808" alt="スクリーンショット 2019-04-01 9 24 52" src="https://user-images.githubusercontent.com/8737743/55299535-5c1c3900-546e-11e9-9476-a72436b61157.png">

2019-04-01 06:23 UTC, eyener3 commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
設定値のこと、ありがとうございます^-^

以下、修正・追加を完了いたしました。

- チームをNoneに

- グループ名（フォルダ名）を変更

- リンク切れがあれば修正

- アサイニーにあいなーを追加

- レビュワーにはゆーとさんとやまたつさんを追加

2019-04-01 10:20 UTC, Riscait commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
よく見たら、コミットが一つしかありません🤔
git push はできましたか❓

2019-04-01 10:49 UTC, eyener3 commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
git pushはやっていませんでした><
帰宅したらすぐに修正します^-^！

2019-04-01 16:57 UTC, eyener3 commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
遅くなりました..
Xcodeからcommit,pushしましたが
違っていたようなので
Gitからやってみています^-^

2019-04-01 17:10 UTC, eyener3 commented on Stepippo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 8PW2QDU8DF;
やってみました^-^

2019-04-01 21:48 UTC, riscait requested changes
フォルフォルダ構成がおかしくなっているようで表示できないファイルがいくつかありました🙅‍♂️
例えば、ViewControllerはViewController.swift/ViewController.swiftというパスになっているようです…！
あいなーさんの環境では、きちんと開けるでしょうか？🤔
<img width="960" alt="スクリーンショット 2019-04-02 6 44 32" src="https://user-images.githubusercontent.com/8737743/55361696-ecac5500-5512-11e9-88de-5a9789d40589.png">
何れにしても、Xcodeで表示されているフォルダ階層と合わせる必要があります👌
例: ViewControllerなら `Classes/Controllers/ViewController.swift`

2019-04-01 22:29 UTC, Riscait commented on Stepippo.xcodeproj/project.pbxproj
> +		8D29221322460A790046917F /* ViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = ViewController.swift; path = ../ViewController.swift/ViewController.swift
```suggestion
		8D29221322460A790046917F /* ViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = ViewController.swift; path = Classes/Controller.swift/ViewController.swift; sourceTree = "<group>"; };
```
おそらく、期待値はこんな感じになると思います👌

2019-04-01 22:30 UTC, Riscait commented on Stepippo.xcodeproj/project.pbxproj
> +		8D29221822460A7F0046917F /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; name = Assets.xcassets; path = ../Assets.xcassets; sourceTree = "<group>"; };
```suggestion
		8D29221822460A7F0046917F /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; name = Assets.xcassets; path = Resources/Assets.xcassets; sourceTree = "<group>"; };
```
多分こんな感じ👌

2019-04-01 22:31 UTC, Riscait commented on Stepippo.xcodeproj/project.pbxproj
> +		8D29221D22460A7F0046917F /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; name = Info.plist; path = ../Info.plist; sourceTree = "<group>"; };
```suggestion
		8D29221D22460A7F0046917F /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; name = Info.plist; path = Resources/Info.plist; sourceTree = "<group>"; };
```
多分こんな感じ👍

2019-04-01 22:32 UTC, Riscait commented on Stepippo.xcodeproj/project.pbxproj
>  		8D29221122460A790046917F /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = "<group>"; };
AppDelegateも、 `Classes/AppDelegate.swift` になるかと👍

2019-04-02 18:12 UTC, eyener3 commented
> フォルフォルダ構成がおかしくなっているようで表示できないファイルがいくつかありました🙅‍♂️
> 例えば、ViewControllerはViewController.swift/ViewController.swiftというパスになっているようです…！
> あいなーさんの環境では、きちんと開けるでしょうか？🤔
> <img alt="スクリーンショット 2019-04-02 6 44 32" width="960" src="https://user-images.githubusercontent.com/8737743/55361696-ecac5500-5512-11e9-88de-5a9789d40589.png">
> 何れにしても、Xcodeで表示されているフォルダ階層と合わせる必要があります👌
> 例: ViewControllerなら `Classes/Controllers/ViewController.swift`

ありがとうございます^-^
引き続き、やってみます！

2019-04-05 00:55 UTC, eyener3 commented
先日のデータ復元させてpushまでやってみました^-^
もし失敗していたら再ローンし直そうと思いますっ
よろしくお願いします^-^

2019-04-05 02:13 UTC, Riscait commented
あいなーさんのMacだとフォルダ構成どうなってます？
スクショ欲しいです！
ぱっと見たところNew Group/AppDelegate.swiftとなっているようですが…

2019-04-05 02:15 UTC, eyener3 commented
もう一度見直してみます^-^
データ戻してaddしたときに
Newgroupも戻ってしまったかもです..
スクショ送りますね

2019-04-05 02:27 UTC, Riscait commented
>もう一度見直してみます^-^ ...

@eyener3 惜しい！
アップデリゲートだけClassesの外に出ちゃってますね！
FinderでClassesの中に移動して、Xcodeからリンクを直せば行けそうですがどうでしょう？？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-04-05 02:29 UTC, Riscait commented
あと、Podfileがまじっているようですね👀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-04-05 02:47 UTC, eyener3 commented
ありがとうございます^0^

2019-04-05 07:02 UTC, eyener3 commented
![スクリーンショット 2019-04-05 16 00 08](https://user-images.githubusercontent.com/45029154/55609564-f0aed000-57bb-11e9-9509-1dda4aa3d849.png)
修正してみました^-^

2019-04-05 07:26 UTC, Riscait commented
>![スクリーンショット 2019-04-05 16 00 08](https://user-images.githubusercontent.com/45029154/55609564-f0aed000-57bb-11e9-9509-1dda4aa3d849.png) ...

@eyener3 おぉ、良さそうですね！
pushしてみてください〜👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-04-05 14:06 UTC, eyener3 commented
@Riscait 
pwdで位置確認したところ、
位置は合っているようでしたが
解決の仕方がわかりませんでした..＞＜
もう少し解決策探してみて困難でしたら
こちら一度クローズし、
新たに再クローンしようと思います^-^

2019-04-05 14:47 UTC, Riscait commented
@eyener3 
今って何が問題なんでしたっけ？
スクショ欲しいです👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-04-05 15:58 UTC, eyener3 commented
階層は合っているはずなのに、
statusするとホームディレクトリのデータが
たくさん一覧で出てくるところが解決しないままでした^-^
再クローンし直してみました^-^。

2019-04-05 20:07 UTC, closed without merging