Feature/ib inspectable
yasasii-team/Stepippo-iOS pull request #131
Opened 2019-05-10 15:24 UTC by Koki-Nakamura

fixes #122 

(#の後にcloseしたいissueの番号を記述してください)

#概要
- [x] CornerRadiusとBorderColorをStoryboardで設定できる様に実装
- [x] StockButtonとAddButtonに上記２点を設定
- [x] AutoLayoutの設定

#スクリーンショット
- iPhoneXR
![Simulator Screen Shot - iPhone Xʀ - 2019-05-11 at 00 22 52](https://user-images.githubusercontent.com/40520484/57538257-fd0de600-7382-11e9-99cd-3feb3b10b76a.png)
- iPad Pro
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-05-11 at 00 22 44](https://user-images.githubusercontent.com/40520484/57538281-0dbe5c00-7383-11e9-8277-c4415f766a81.png)

#注意点
なぜかBorderColorが正しく反映されない
別でIssueを立てます。

2019-05-11 01:23 UTC, riscait requested changes
AutoLayoutのエラーが残ってますね…！ちょっと見てみます。

（すみません、書いていなかったかもしれないのですが、GitFub Flowを使うので、次回以降のブランチ名には`feature/`を入れなくても大丈夫です🙆‍♂️）
https://gist.github.com/Gab-km/3705015

2019-05-11 01:23 UTC, Riscait commented on Stepippo/Classes/Util/UIView+Extension.swift
> +    @IBInspectable var borderColor: UIColor? {
borderWidthを追加することで、ボーダー表示されるかと思います👌
```swift
    @IBInspectable var borderWidth: CGFloat {
        get {
            return layer.borderWidth
        }
        set {
            layer.borderWidth = newValue
        }
    }
```

2019-05-11 01:42 UTC, Riscait commented
①2つのボタンは並んでいるのでStackViewに入れてしまった方がAutoLayoutが簡単になるかと思います🙆‍♂️
②Labelのbottom制約が重複していました👌
③TextFieldの高さがもう少しあった方が入力しやすそうです(36くらい？)
<img width="144" alt="スクリーンショット 2019-05-11 10 41 43" src="https://user-images.githubusercontent.com/8737743/57563493-80f2bd00-73d9-11e9-8b12-78dd00a3c12f.png">

2019-05-12 08:17 UTC, Koki-Nakamura commented on Stepippo/Classes/Util/UIView+Extension.swift
> +    @IBInspectable var borderColor: UIColor? {
あぁ〜！
完全にボケてましたw
修正しました。

2019-05-12 08:28 UTC, riscait requested changes
①LabelとTextFieldの間の制約が同じものが2つ残ったままでした…！

②button2つとも高さを設定しているのでequal heightしているのは冗長ですね👌
stackViewを使用しないのであれば、どちらか一つだけに高さを設定して、equal heightとするのが良いと思います🙆‍♂️

2019-05-12 08:30 UTC, Riscait commented on Stepippo/Classes/Util/UIView+Extension.swift
> +    @IBInspectable var borderColor: UIColor? {
boarderが表示されていることを確認しました✨

2019-05-12 08:33 UTC, Koki-Nakamura commented
指摘いただいた箇所を修正しました！
再レビューお願いします。

2019-05-12 09:18 UTC, riscait approved these changes
制約の修正を確認しました🙆‍♂️

2019-05-12 09:31 UTC, merged