StackViewのAutoLayout設定
yasasii-team/Stepippo-iOS pull request #146
Opened 2019-05-17 11:50 UTC by eyener3

fixes #141 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- StackViewのAutoLayout設定を行ないました

### Other Information(他の情報)

- 期間変更とタスク選択のボタンに枠をつけてみました

### Tested(テストしたこと)

- 各デバイスでのシミュレーションテストXR
各デバイス：XR,Xs,XsMax,X,SE
![スクリーンショット 2019-05-17 20 37 16](https://user-images.githubusercontent.com/45029154/57926028-2a0f4b00-78e5-11e9-8359-43ca35bf0624.png)

よろしくお願いいたしますm(._.)m💡

2019-05-17 13:58 UTC, riscait requested changes
お疲れ様です！
SE~Maxで崩れることなく表示されることを確認しましたー！

あとは、SEで表示した時に「期間変更」と「残り2日」の文字が切れてしまっている所だけ修正しておきましょうか！（惜しい）

ラベルをまとめているStackViewのSpacingが100を超える数値になっていました。
これを小さい値にして、DistributionをEqual Spacingなどに変更すると、一先ずは解決するかと思います👌

2019-05-17 14:02 UTC, eyener3 commented
ありがとうございます！
文字が切れているところ、修正してみます^-^💡

2019-05-17 14:06 UTC, Riscait commented
今previewではなく、シミュレータで確認してみたら途切れてはいませんでした！
が、直しておいた方が良いかもですね👌

角丸がうまく表示されていませんでした。
Kokiさんが追加してくださったUIView Extensionの角丸はUIButtonでの使用は相性悪いのかな？
![Simulator Screen Shot - iPhone SE - 2019-05-17 at 23 01 08](https://user-images.githubusercontent.com/8737743/57933471-5e403700-78f8-11e9-9c12-c1ee03cdd96e.png)

2019-05-17 14:53 UTC, eyener3 commented
SEでの文字切れ、ボタン、ProgressBarのレイアウトを修正しました^-^💡
![スクリーンショット 2019-05-17 23 47 20](https://user-images.githubusercontent.com/45029154/57936423-e295b880-78fe-11e9-90dd-efe2c3051d60.png)

2019-05-17 23:40 UTC, riscait requested changes
すごい！ボタンの枠線が綺麗になっていることを確認しました！
ただ、制約のエラーが残っています(>_<)
<img width="266" alt="スクリーンショット 2019-05-18 8 32 11" src="https://user-images.githubusercontent.com/8737743/57961218-7b045b00-7948-11e9-98c7-20e27ff81a49.png">

2019-05-18 06:20 UTC, eyener3 commented
ありがとうございます^-^💡

2019-05-18 07:05 UTC, eyener3 commented
今度こそ、うまくいきました^-^💡
![スクリーンショット 2019-05-18 16 01 07](https://user-images.githubusercontent.com/45029154/57965965-b32a8e80-7986-11e9-9384-52d1ca9afbd4.png)
![スクリーンショット 2019-05-18 16 01 38](https://user-images.githubusercontent.com/45029154/57965966-b6257f00-7986-11e9-9b33-00af493b13d6.png)

2019-05-18 07:09 UTC, eyener3 commented
他のデバイスが不恰好になるのですが
しかたがないのですかね。。(^◇^;)
![スクリーンショット 2019-05-18 16 08 20](https://user-images.githubusercontent.com/45029154/57966010-4cf23b80-7987-11e9-8fbe-11e2b8db1b80.png)

2019-05-18 07:24 UTC, riscait approved these changes
お疲れ様です！
エラーは解決できたとのことなので、こちらでOKとして実装に入っていきましょう！👌

続きは、手の空いた時かAutoLayoutについて理解が深まった時に修正していきましょう😊

2019-05-18 08:43 UTC, eyener3 commented
ありがとうございます！☺️🙏
はいっ、AutoLayoutについては、
今後も学んでいこうと思います♪🙇🏻‍♀️

2019-05-18 08:50 UTC, merged