IPPOのデータモデルを作成
yasasii-team/Stepippo-iOS pull request #147
Opened 2019-05-18 11:29 UTC by naipaka

fixes #140

### Summary(要約)
IPPOのデータモデルを作成しました。
項目は以下の通りです。( #42 )
- 一意のID
- 名前
- 進捗状態（後でやる・挑戦中・達成見込・達成済み）
- 挑戦タスクを追加した日時
- 実施済みにした日時（チェックをつけた日時）

### Tested(テストしたこと)
- ビルドの確認

### レビューポイント
- 命名の確認
- 進捗状態を表す単語の確認
- そもそも進捗状態はStringで表して良いか、他にいい方法があるか

### Must Reviewer(必須レビュアー)

2019-05-18 12:16 UTC, riscait requested changes
お疲れ様です！レビューしました🙇‍♂️

2019-05-18 12:16 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var status = ""
enumを使う方法が良さそうです！

```swift
enum IPPOStatus: String {
    case stock
    case challenging
    case performed
    case achieved
}
```
```swift
    dynamic private var status = ""
    
    var ippoStatus: IPPOStatus {
        get {
            return IPPOStatus(rawValue: status)!
        }
        set {
            status = newValue.rawValue
        }
    }
```
参考記事:
https://qiita.com/nohirap/items/3b5e30b505d8808f6ce7

2019-05-18 12:16 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var primaryKey = 0
一意のIDにはプライマリキーを使いましょう👌
https://realm.io/docs/swift/latest#primary-keys

2019-05-18 12:16 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var addDateTime: Date?
追加日時は最初から必要なプロパティなのでオプショナルじゃなくても良いかと思いました👌

2019-05-18 12:40 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var status = ""
なるほど…！enumはこういう使い方があるんですね…！勉強になります:bow:
修正します！

2019-05-18 12:44 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var primaryKey = 0
プライマリーキーの設定方法知りませんでした…！ありがとうございます！
修正します！

2019-05-18 12:45 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var addDateTime: Date?
確かに現在日時を入れればいいですね！修正します！

2019-05-18 13:00 UTC, naipaka commented
レビューありがとうございます！
該当箇所修正しました！🙇

2019-05-18 13:44 UTC, riscait requested changes
修正ありがとうございます！
何度も手元で試しているんですが、IPPOをうまく保存ができません…！

このオブジェクトをエラーなくRealmで書き込みして読み込めるところまでがゴールとしてもらっても良いでしょうか？

```swift
        let realm = try! Realm()
        try! realm.write {
            ...
        }
```
（realmのメソッドで試す）

2019-05-18 13:44 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +class IPPO: Object {
@objcをつけないとこのクラスを使用しようとした時にエラーになりました！
classsの前に@objcMembersを付与しましょう！
```swift
@objcMembers
class IPPO: Object {
```
https://realm.io/docs/swift/latest/

2019-05-18 13:44 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
手元で何度か試しているんですが、statusが保zんできないようです…！なんでだろう？

2019-05-18 15:06 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +class IPPO: Object {
ビルドしか試してませんでした…！
了解です！

2019-05-18 15:06 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
少し調べてみます！

2019-05-18 15:32 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
おぉ！僕わからなかったので…一旦調査を諦めました笑

2019-05-18 15:47 UTC, naipaka commented
![image](https://user-images.githubusercontent.com/45661924/57971954-ab430c80-79cf-11e9-9cce-1263a82746d3.png)
こんな感じで書き込めました！

2019-05-18 15:55 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
https://qiita.com/hosopy/items/31a0f76650074c1b75bf

こちらの記事ではプロパティがprivateになっていなかったので、外してみたらいけました
けど正しい解決方法じゃないかもしれないですね。。。

2019-05-18 16:00 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
そもそもenumで定義されてる以外のものを設定できないようにするためにprivateにしてるからダメか。

2019-05-18 16:00 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    var status: IPPOStatus {
ほんとだ、この記事Javaだけ見てそっ閉じしてました☺️笑
Private外して記録できること確認しました！！
正しい解決方法だと思います！

2019-05-18 16:02 UTC, Riscait commented
修正ありがとうございます！

privateを外したことによって、statusとippoStatusが両方クラス外から見えるようになってしまって紛らわしいですね🤔わかりやすい名前を考えましょうか？

2019-05-18 16:07 UTC, Riscait commented
使ってほしい方がstatusで、使って欲しくない方(旧private)の候補出してみます🙋‍♂️

- _status (privateっぽい)
- privateStatus (他に用途がありそうに見える？)
- st (わかりにくくして使いにくくしてみた)
- innerStatus (中の？)
- statusString (ただの文字列だよと主張してみた)

🤔

2019-05-18 16:39 UTC, naipaka commented
privateでも書き込めるっぽい？です
realm browserには表示されないんですが、print(ippo.status)で見ると設定できてますね🤔

![image](https://user-images.githubusercontent.com/45661924/57972516-e1d05580-79d6-11e9-9e5c-fe58fb1a9f0d.png)

![image](https://user-images.githubusercontent.com/45661924/57972508-b9e0f200-79d6-11e9-8382-b740a2d04726.png)

2019-05-18 16:44 UTC, Riscait commented
> privateでも書き込めるっぽい？です
> realm browserには表示されないんですが、print(ippo.status)で見ると設定できてますね🤔

realm.objects〜でstatusを取得できますか？🤔
取得できれば = 保存できているになりそうですが…

2019-05-18 17:09 UTC, naipaka commented
> realm.objects〜でstatusを取得できますか？🤔
> 取得できれば = 保存できているになりそうですが…

追加した内容を出力してるだけだから表示されるのは当たり前でしたごめんなさい！:sweat_drops:
realm.objects〜ではいけませんでしたね…

2019-05-18 17:18 UTC, naipaka commented
privateを使わない場合の変数の候補は
- _status 
- statusString
が個人的にいいですね

2019-05-18 23:44 UTC, Riscait commented
> privateを使わない場合の変数の候補は
> 
> * _status
> * statusString
>   が個人的にいいですね

_statusにしちゃいましょうか☺️

2019-05-18 23:58 UTC, Riscait commented
ドキュメントを読んでいたら、
「一意の自動生成値が必要なほとんどの状況では、連続した連続した整数IDを持つ必要はありません。通常、一意の文字列主キーで十分です」
って書かれてました笑

確かに、連番にこだわりなければランダムな文字列(UUID)で良いなと思いました…
https://realm.io/docs/swift/latest#limitations-models

2019-05-19 01:37 UTC, naipaka commented
> ドキュメントを読んでいたら、
> 「一意の自動生成値が必要なほとんどの状況では、連続した整数IDを持つ必要はありません。通常、一意の文字列主キーで十分です」
> って書かれてました笑
> 
> 確かに、連番にこだわりなければランダムな文字列(UUID)で良いなと思いました…
> https://realm.io/docs/swift/latest#limitations-models

おっ！ドキュメント読むのやっぱり大事ですね〜
ではランダムな文字列にしようと思います！
privateを使わない場合の変数も修正しますね☺️

2019-05-19 01:49 UTC, naipaka commented
修正しました！
再レビューお願いします！
![image](https://user-images.githubusercontent.com/45661924/57976778-b58ef600-7a23-11e9-9014-0f716a628311.png)

2019-05-19 01:54 UTC, riscait submitted a review, later dismissed
細かいですが一点だけコメントしました！
それ以外OKです！ありがとうございます😊

2019-05-19 01:54 UTC, Riscait commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var id = NSUUID().uuidString
NSつかない方で良いかと思います👌
https://developer.apple.com/documentation/foundation/uuid

2019-05-19 01:59 UTC, naipaka commented on Stepippo/Classes/Models/IPPO.swift
> +    dynamic var id = NSUUID().uuidString
そうなんですね！修正します！
NSUUIDとUUIDの違いがわからなかったので調べておきます:triumph:

2019-05-19 02:03 UTC, naipaka commented
修正しました！何から何までレビューしてもらってありがとうございます:bow:

2019-05-19 02:06 UTC, riscait approved these changes
お疲れ様です😊
こちらこそ細かいところにも付き合っていただきありがとうございます！

2019-05-19 03:17 UTC, naipaka commented
承認ありがとうございます！マージします！

2019-05-19 03:18 UTC, merged