チェックボタンのアニメーションを実装
yasasii-team/Stepippo-iOS pull request #161
Opened 2019-05-25 23:06 UTC by eyener3

fixes #156 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- チェックボタンのアニメーションを実装

### Other Information(他の情報)

- 今後、checkButtonのImageを変える可能性アリ

### Tested(テストしたこと)

- ビルドエラーがないこと

- シュミレーターにてチェックボタンが正常にアニメーションし切り替わること

[![Image from Gyazo](https://i.gyazo.com/37a229e3930c326166838dde349c9633.gif)](https://gyazo.com/37a229e3930c326166838dde349c9633)

【実装画面】
![スクリーンショット 2019-05-26 08 00 37](https://user-images.githubusercontent.com/45029154/58375395-f8ede500-7f8c-11e9-86e9-8c2b20d29afa.png)

### Must Reviewer(必須レビュアー)

2019-05-25 23:23 UTC, riscait requested changes
お疲れ様です！
全く同じ処理を書かなくても良いように、関数にまとめましょう👌
senderを引数として渡して、 `private func doMethod(sender:)`を定義すると良いかと思います👍

今回も `.toggle()` が使えそうな位置がありますね🙆‍♂️

2019-05-26 00:00 UTC, eyener3 commented
ありがとうございます！(＞人＜;)
さっそく取り組んでみますっ💡

2019-05-26 00:15 UTC, Sab-swiftlin commented on Stepippo/Classes/Controllers/ProgVC.swift
> +        UIView.animate(withDuration: 0.5, delay: 0.1, options: .curveLinear, animations: {
一般的にインターフェースのアニメーションは200ms~500msが良いとされています。
今の設定だと一回のアニメーションに1秒かかっているので、アプリの動きがが重く見えユーザーにストレスを与えてしまう可能性があります。
Durationを半分かそれ以下にすると良いかもしれません。

2019-05-26 00:21 UTC, eyener3 commented on Stepippo/Classes/Controllers/ProgVC.swift
> +        UIView.animate(withDuration: 0.5, delay: 0.1, options: .curveLinear, animations: {
> 一般的にインターフェースのアニメーションは200ms~500msが良いとされています。
> 今の設定だと一回のアニメーションに1秒かかっているので、アプリの動きがが重く見えユーザーにストレスを与えてしまう可能性があります。
> Durationを半分かそれ以下にすると良いかもしれません。

Sabさん、ありがとうございます！
たしかに動きが遅くみえてしまっていますね＞＜💡
さっそく修正してみますっ!!(*´ｰ｀)ゞ

2019-05-26 15:13 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +        UIView.animate(withDuration: 0.5, delay: 0.1, options: .curveLinear, animations: {
今行なっている修正の後でいいのですが、
optionsに .autoreverseを追加すると自動で逆再生してくれるそうです！
`UIView.animate(withDuration: duration, delay: delay, options: [.curveLinear, .autoreverse], animations: {`

参考記事: https://qiita.com/hachinobu/items/57d4c305c907805b4a53#uiviewanimate%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

2019-05-26 15:22 UTC, eyener3 commented on Stepippo/Classes/Controllers/ProgVC.swift
> +        UIView.animate(withDuration: 0.5, delay: 0.1, options: .curveLinear, animations: {
ありがとうございます！
やってみます^-^💡

2019-05-26 15:55 UTC, eyener3 commented
**修正箇所**

- アニメーション処理の関数化

- アニメーションの速度

- アニメーションの自動逆再生

[![Image from Gyazo](https://i.gyazo.com/9809c5f7ffbf0414ae4fb092f89fbe81.gif)](https://gyazo.com/9809c5f7ffbf0414ae4fb092f89fbe81)

2019-05-26 23:45 UTC, riscait approved these changes
新しい定義と、修正箇所を確認しました🙆‍♂️

2019-05-27 11:28 UTC, Sab-swiftlin approved these changes
動きが軽やかになってとても良いですね！
あとは好みの問題になりますので、あいなーさんが触ってみて心地良く感じるのはどのパターンか色々試してみると面白いかもしれません。

2019-05-27 11:42 UTC, Riscait commented
> あとは好みの問題になりますので、あいなーさんが触ってみて心地良く感じるのはどのパターンか色々試してみると面白いかもしれません。

とても同意です☺️あいなーさんの好みで色々調整してください✨

2019-05-27 11:48 UTC, eyener3 commented
Sabさん、龍之介さん、
ありがとうございます^0^！！

2019-05-27 11:48 UTC, merged