プロジェクト設定
yasasii-team/Stepippo-iOS pull request #168
Opened 2019-05-27 23:22 UTC by eyener3

fixes #11 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- Issueの通り、設定しました

![スクリーンショット 2019-05-28 08 10 16](https://user-images.githubusercontent.com/45029154/58441853-94fc2580-8120-11e9-9321-7587250b05cd.png)

![スクリーンショット 2019-05-28 08 10 10](https://user-images.githubusercontent.com/45029154/58441846-8746a000-8120-11e9-90c4-4bb491646e02.png)

### Other Information(他の情報)

- 以下（画像）「このブランチは自動的にマージされました」とメッセージがでていました

プルリクする必要がなかったら、ごめんなさい(＞人＜;)..

![スクリーンショット 2019-05-28 08 16 35](https://user-images.githubusercontent.com/45029154/58441954-721e4100-8121-11e9-9b9b-8010fb2b97ac.png)

2019-05-27 23:50 UTC, Riscait commented
ありがとうございます！
「マージ可能なブランチ」って意味ですね🙆‍♂️
のちほど確認します👌


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-05-28 14:30 UTC, riscait requested changes
細かいですが…Versionが変わってなかったです！

2019-05-30 01:51 UTC, eyener3 commented
> 細かいですが…Versionが変わってなかったです！

あら。。すみません(＞人＜;)
すぐに修正いたします！

2019-05-30 02:37 UTC, eyener3 commented
こちら修正いたしました💡
どなたでも大丈夫ですので、承認いただけると有難いです^0^
![スクリーンショット 2019-05-30 11 34 54](https://user-images.githubusercontent.com/45029154/58604379-172a4c80-82cf-11e9-9e42-c85ffb57ead9.png)

2019-05-30 06:16 UTC, Sab-swiftlin approved these changes
LGTM

2019-05-31 08:20 UTC, riscait approved these changes

2019-05-31 08:24 UTC, merged