Update issue templates
yasasii-team/Stepippo-iOS pull request #18
Opened 2019-04-04 10:36 UTC by YamaTatsu10969

2019-04-04 11:04 UTC, yamatatsu10969 reviewed
不必要なファイルを削除しました。

2019-04-04 12:13 UTC, riscait requested changes
少しだけ変更依頼を書きました！

2019-04-04 12:13 UTC, Riscait commented on .github/ISSUE_TEMPLATE/------------.md
> +name: タスクやリファクタリング
Task or Refactoring のように英語にすると、ファイル名にも反映されるので英語にしましょう👍

2019-04-04 12:13 UTC, Riscait commented on .github/ISSUE_TEMPLATE/-------.md
> +name: 機能追加・改善
こちらもですね！

2019-04-04 12:13 UTC, Riscait commented on .github/ISSUE_TEMPLATE/-------.md
> +assignees: YamaTatsu10969
assigneesは空にしておきましょう👌

2019-04-04 12:13 UTC, Riscait commented on .github/ISSUE_TEMPLATE/------.md
> +name: バグレポート
こちらも英語にしましょう🇺🇸

2019-04-04 13:47 UTC, yamatatsu10969 reviewed
修正しました！レビューお願いします！

2019-04-04 13:53 UTC, riscait approved these changes
レビューへの対応を確認しました🙆‍♂️
マージして、ブランチを削除しちゃってください😊👍

2019-04-05 09:41 UTC, merged

2019-04-05 09:41 UTC, YamaTatsu10969 commented
できました！ありがとうございます。