Stock realm
yasasii-team/Stepippo-iOS pull request #198
Opened 2019-06-14 23:55 UTC by minmin0530

fixes #186
### Summary(要約)
後でやるボタンで後でやるリストにIPPOを登録

### Other Information(他の情報)

### Tested(テストしたこと)

### Must Reviewer(必須レビュアー)

2019-06-15 02:17 UTC, riscait requested changes

2019-06-15 02:17 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        ippo.id = "1"
1. classかextensionで RealmObjectAccesibleに準拠すると、より簡単にRealm.writeが行えるかと思います👌
2. IPPOのidはUUIDが初期値で付与されますので指定しなくても大丈夫です🙆‍♂️
1. addDateTimeも初期値でData()が設定されているかと思います。
2. performedDateTimeは達成した日付なのでStockでは見設定にしましょう！

2019-06-15 02:43 UTC, minmin0530 commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        ippo.id = "1"
https://github.com/yasasii-team/Stepippo-iOS/pull/154#issuecomment-495931417
これを参考にRealmObjectAccesibleに準拠する書き方に修正してみます。

2019-06-15 06:05 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        ippo.id = "1"
おぉ〜見つけてくださってありがとうございます！

2019-06-15 23:11 UTC, riscait requested changes
お疲れ様です！
いくつかコメントしました👌
レビュワーに「iOS（チーム）」
アサイニーにご自分を追加していただければと思います😊👌

2019-06-15 23:11 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +import RealmSwift
RealmObjectAccessibleを使うのであれば、 `let realm = try! Realm()` を使用しないのであれば、importは不要となります👌

2019-06-15 23:11 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +    let realm = try! Realm()
こちらも、RealmObjectAccessibleを使って `write(ippo)`をするのであれば、Realmをインスタンス化は不要となります🙆‍♂️

2019-06-15 23:11 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        ippo.status = IPPOStatus.stock
`IPPOStatus` は省略して、`.stock`という書き方が可能です👌

2019-06-16 00:16 UTC, riscait requested changes
修正ありがとうございます！
1点コメントしました👌

2019-06-16 00:16 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        if addTaskTextField.text != nil && addTaskTextField.text != "" {
```suggestion
        if let inputText = addTaskTextField.text, !addTaskTextField.text.isEmpty {
```
のように書くと、if の波括弧内で今日西安ラップの必要なく、`inputText`という名前で使えるようになります👌
空文字判定はisEmptyが使えますね🙆‍♂️

2019-06-16 00:26 UTC, minmin0530 commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        if addTaskTextField.text != nil && addTaskTextField.text != "" {
このあたりから #199 の領域に入ってます(^_^;)

2019-06-16 00:29 UTC, Riscait commented on Stepippo/Classes/Controllers/GoalSettingVC.swift
> +        if addTaskTextField.text != nil && addTaskTextField.text != "" {
はい、ちょっと入っちゃいましたね👌🤔

2019-06-16 00:30 UTC, riscait approved these changes
修正ありがとうございます！
確認しました！
動作に問題なければマージお願いします☺️

2019-06-16 00:38 UTC, merged