残り期間をLabelに表示する
yasasii-team/Stepippo-iOS pull request #201
Opened 2019-06-16 12:47 UTC by eyener3

fixes #180 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- UserDefaultsで現在日時を取得

- UserDefaultsで現在日時と残り期間の差分を算出

- 算出した残り期間をLabelに表示する

### Other Information(他の情報)

- Label表示が途切れているが、後に改行などで修正する

### Tested(テストしたこと)

- 現日時と残り期間の差分がLabelに表示されること

![Screen Shot 0001-06-16 at 9 06 53 PM](https://user-images.githubusercontent.com/45029154/59564320-4935ff80-9080-11e9-80c5-d52c49be5c89.png)

2019-06-16 13:46 UTC, riscait requested changes
お疲れ様です☺️
いくつかコメントを入れました👌

2019-06-16 13:46 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +            // TODO: 毎日の場合の計算
こちら、完了しているならTODOコメントはケイタほうが良いですね🙆‍♂️

2019-06-16 13:46 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +            // 設定されていない場合の初期値は31日（月末）とする
こちら、実装とコメントに差異があるので、コメントを消すか書き換えたほうが良いですね👌

2019-06-16 13:46 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +            // TODO: 毎月の場合の計算
こちらもTODOは決して良さそうですね👌

2019-06-16 13:46 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +    @IBOutlet weak var cycleLabel: UILabel!
どこに繋いで書いても動作はしますが、分かりやすいように@IBOutletプロパティは上の方に記述したほうが良いですね👌
class宣言の直後（Line:13）あたりがオススメです🙆‍♂️

2019-06-16 13:46 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +        _ = userDefaults.string(forKey: "deadlineCycle") ?? "deadlineCycleは保存されていません"
こちら、使用していないのであれば削除したほうが良い行ですね🙆‍♂️
合わせてUserDefaultsのインスタンスも使っていないのでここでは不要だと思います👌

2019-06-16 16:12 UTC, eyener3 commented
> お疲れ様です☺️
> いくつかコメントを入れました👌

ありがとうございます！
指摘箇所、修正いたします^-^💡

2019-06-17 09:50 UTC, riscait approved these changes
LGTM🎉

2019-06-17 09:51 UTC, eyener3 commented
> LGTM🎉

ありがとうございます☺️🎉

2019-06-17 09:51 UTC, merged