PRのテンプレートを追加
yasasii-team/Stepippo-iOS pull request #23
Opened 2019-04-05 10:52 UTC by YamaTatsu10969

作成しました！ご確認よろしくお願いします！

2019-04-05 12:26 UTC, riscait requested changes
fixes # いいですね！
2点追加お願いしたいです👌

2019-04-05 12:26 UTC, Riscait commented on .github/pull_request_template.md
> +
`### テストしたこと`
と
`### 必須レビュアー`

も追加しましょうか👌

原則、PRにはチームメンバー全員をレビュワーに入れて、
もし必ずみて欲しい人がいたら、「必須レビュワー」でメンションするようにしていきましょう！

2019-04-07 02:03 UTC, YamaTatsu10969 commented on .github/pull_request_template.md
> +
かしこまりました！

2019-04-07 03:28 UTC, riscait approved these changes

2019-04-07 03:28 UTC, riscait approved these changes
お疲れ様です！変更確認しました👌

2019-04-07 07:07 UTC, eyener3 reviewed
確認いたしました💡

2019-04-07 12:35 UTC, merged

2019-04-07 12:35 UTC, YamaTatsu10969 commented
ありがとうございます！

2019-04-07 12:50 UTC, Riscait commented
お疲れ様でした🎉！
Delete Branchしておきました👍