進捗画面の実装ファイル作成
yasasii-team/Stepippo-iOS pull request #41
Opened 2019-04-08 20:16 UTC by eyener3

fixes #30 

(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)

- Prog.storyboard

- ProgCell.xib

- ProgVC.swift

- ProgCell.swift

### Other Information(他の情報)
Prog.storyboardが何も表示されないので原因究明をはかる。
ファイルが明らかにおかしくなっている模様。
![スクリーンショット 2019-04-09 05 07 44](https://user-images.githubusercontent.com/45029154/55753805-2dade780-5a86-11e9-8651-5ec739c8baad.png)

### Tested(テストしたこと)
・シュミレーター（2つとも画面がまっしろ）
・リンク切れの可能性の確認

### Must Reviewer(必須レビュアー)

2019-04-08 22:45 UTC, riscait requested changes
あいなーさん、お疲れ様です👌！

①追加したstoryboardには最初は何も入っていないため、何も表示されないのが正常となります🙆‍♂️
ViewControllerとNavigationControllerを追加しましょう！

②最初に表示される画面を変更していないためMain.storyboardが表示されるので真っ白となっています。
表示させたい時はMain Interfaceを表示させたい画面に変更しましょう👌
![image](https://user-images.githubusercontent.com/8737743/55761278-b4b88b00-5a99-11e9-9871-751308e500bc.png)

③この画面ではおそらくTableViewを使用しない方が良いんじゃないかと思いました🤔
そうなるとCellは不要になりますね👌
画面定義書で、どのパーツは何を使うという設計も並行して行なっていくのも良いかもしれないですね💡

2019-04-08 22:45 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgVC.swift
> +import Foundation
VCなどのUIファイルを追加する時は、Cocoa Touch Class を選択しましょう👌
SubClassを選べるのでUIViewControllerを選べば、UIViewControllerを継承したクラスを作成してくれます👍
![image](https://user-images.githubusercontent.com/8737743/55760796-242d7b00-5a98-11e9-89a9-e60cb627475a.png)

2019-04-08 22:45 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgCell.swift
> +import Foundation
TableViewCellもCocoaTouchClassから新規作成します👌
その時 Also create XIB file にチェックを入れると、xibファイルも自動で一緒に作られますので便利です😊

2019-04-09 02:59 UTC, eyener3 commented
たくさん教えていただきまして、
本当にありがとうございます^-^！
もう一度やってみようと思いますっ

2019-04-09 14:19 UTC, eyener3 commented
修正いたしました。
![スクリーンショット 2019-04-09 23 18 49](https://user-images.githubusercontent.com/45029154/55807845-e2471800-5b1d-11e9-8aed-67100a25eff2.png)

2019-04-09 14:31 UTC, riscait requested changes
File changed を見れば分かるのですが、ProgCellのファイルが残っていますね。
ひょっとして、ファイルをDeleteするときにRemove Referenceを選択したのではないですか？
基本的にMove to Trash を選択して、参照だけでなく、ファイル自体も削除しましょう👍
Remove Referenceでは、Xcode上から消えるだけで、ファイル自体は残ったままとなります🚮

2019-04-12 01:45 UTC, riscait approved these changes

2019-04-12 01:46 UTC, riscait requested changes
すみません、Approveミスです。

2019-04-14 00:46 UTC, yamatatsu10969 reviewed
よきです！！！！

2019-04-14 00:46 UTC, YamaTatsu10969 commented on Stepippo/Classes/Controllers/ProgCell.swift
> +import Foundation
@Riscait 
ViewsにCellも含めるんですね！

2019-04-14 00:51 UTC, Riscait commented
@YamaTatsu10969 
すみません、僕が間違えちゃったんですが、Cell.swiftはViewsですね！

2019-04-14 00:53 UTC, Riscait commented on Stepippo/Classes/Controllers/ProgCell.swift
> +import Foundation
@YamaTatsu10969　@yasasii-team/ios 
すみません、僕が間違えちゃったんですが、Cell.swiftはViewsです！👌

2019-04-17 13:52 UTC, Riscait commented
@eyener3 
とりあえず、このPRは削除して、最新のmasterからブランチ切るのが楽かと思います🙆‍♂️
そして、以下のファイルを追加

- Prog.storyboard
- ProgVC.swift

2019-04-17 14:10 UTC, eyener3 commented
@Riscait 
承知しました^0^！
もう一度やってみますねっ💡
ありがとうございます😊

2019-04-17 14:11 UTC, closed without merging