進捗画面のstoryboardとそれに対応するUIViewControllerファイルを作成
yasasii-team/Stepippo-iOS pull request #66
Opened 2019-04-19 07:27 UTC by eyener3

fixes #
#30 
(#の後にcloseしたいissueの番号を記述してください)

### Summary(要約)
以下のファイルを作成しました。

- Prog.storyboard

- ProgVC.swift

- ProgVC.xib

### Other Information(他の情報)

- [ ] また前と同じエラーが出る。後ほど、修正してみます。

- [ ] いまいち、commitのコツ（仕組み）が掴めない。
![スクリーンショット 2019-04-19 16 25 31](https://user-images.githubusercontent.com/45029154/56412650-da2a6d80-62bf-11e9-89bb-853e4bf3628d.png)

### Tested(テストしたこと)

### Must Reviewer(必須レビュアー)

2019-04-19 08:07 UTC, eyener3 commented
ファイルを作成した時ではなく、
ライブラリを設置したときにエラーになるようなので、
その方向で解決策をググってみる。

2019-04-19 09:00 UTC, Riscait commented
とりあえず最新のmasterから切ってやりましょう><b

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-04-19 09:22 UTC, eyener3 commented
これで切ったのだと思ったのですが、
まだ切れていないのですね..
どうしたら視覚的判断ができるのか、
なかなかムズカシイです。。><
![スクリーンショット 2019-04-19 18 19 46](https://user-images.githubusercontent.com/45029154/56417746-d3a3f200-62cf-11e9-874f-c140ad3748ad.png)

2019-04-19 09:55 UTC, Riscait commented
git log コマンドで現在のブランチのコミット履歴が見れますよ👌

2019-04-19 10:00 UTC, Riscait commented
これはGitHub上で二つのブランチを撮影したものですが、
こうして見比べてみるとmasterの途中までしかないことがわかります👌

![A79A1E01-FF0D-4E03-9124-AFB12D68C66B](https://user-images.githubusercontent.com/8737743/56419436-351a8f80-62d5-11e9-8db0-901b4f5cd72d.jpeg)
![13A9F7FD-3595-4486-B8B2-799D90EC2CF4](https://user-images.githubusercontent.com/8737743/56419437-351a8f80-62d5-11e9-915e-aa1a0f6d9048.jpeg)

2019-04-19 10:03 UTC, Riscait commented
①xibファイルを後から追加していますが、使いますか？
使うなら良いのですが…👍

②Storyboard上のViewControllerのクラスをProgVCに変えていなければ変えましょう👌

2019-04-19 10:06 UTC, eyener3 commented
> これはGitHub上で二つのブランチを撮影したものですが、
> こうして見比べてみるとmasterの途中までしかないことがわかります👌
ありがとうございます^-^。

2019-04-19 10:07 UTC, eyener3 commented
> ①xibファイルを後から追加していますが、使いますか？
> 使うなら良いのですが…👍
> 
> ②Storyboard上のViewControllerのクラスをProgVCに変えていなければ変えましょう👌
xib、いるかどうかの判断はよくわかっておらず、すみません。
消しておきますねっ^-^。

2019-04-20 19:43 UTC, eyener3 commented
再レビューよろしくお願いします^-^
コンフリクトの解消も行ないました。

2019-04-20 20:32 UTC, eyener3 reviewed
コンフリクトの解消を行ないました。

2019-04-20 20:51 UTC, eyener3 commented
![スクリーンショット 2019-04-19 16 21 29](https://user-images.githubusercontent.com/45029154/56462031-18767880-63f7-11e9-8dae-d50c2e277a5c.png)

上記のエラーでつまづいていましたが、
下記にように、IDを設けることで解決いたしました。

![スクリーンショット 2019-04-21 05 26 37](https://user-images.githubusercontent.com/45029154/56462033-1dd3c300-63f7-11e9-81cc-3f691f423851.png)

よろしくお願いしますm(._.)m

2019-04-21 00:43 UTC, riscait requested changes
手元で動作確認や、File changedの確認は行いましたか？
Prog関連ファイルがすべて消えて無くなっています。

2019-04-21 00:49 UTC, Riscait commented
> 上記のエラーでつまづいていましたが、
> 下記にように、IDを設けることで解決いたしました。

IDではなく、最初に表示するVCを指定していないのが原因かと思われます👌
詳しくは is initial view controller でググると出てくると思います。

また、NavigationControllerとVCが繋がっておらず、ただ隣に置いてあるだけのように見えます。
（NCを追加する方法）
<img width="751" alt="スクリーンショット 2019-04-21 9 47 36" src="https://user-images.githubusercontent.com/8737743/56463998-9a2bcd80-641a-11e9-8998-a02bb799babe.png">

2019-05-01 15:31 UTC, eyener3 commented
再クローンし直すので、
一度こちらクローズいたします。

2019-05-01 15:31 UTC, closed without merging